'use client';

import { LogoLoader } from "@workspace/ui";
import { useState, useEffect } from 'react';
import { X, FileText, CheckCircle, Target, Sparkles, Download, ExternalLink } from 'lucide-react';
import api from '@/lib/api';
import toast from 'react-hot-toast';
import clsx from 'clsx';

interface MeetingSummaryModalProps {
    roomId: string;
    onClose: () => void;
}

export default function MeetingSummaryModal({ roomId, onClose }: MeetingSummaryModalProps) {
    const [summary, setSummary] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchSummary = async () => {
            try {
                const { data } = await api.get(`/api/meeting/ai/summary/${roomId}`);
                setSummary(data.summary);
            } catch (err) {
                console.error('Failed to fetch summary:', err);
                toast.error('Could not find AI summary for this meeting.');
                onClose();
            } finally {
                setLoading(false);
            }
        };

        fetchSummary();
    }, [roomId, onClose]);

    if (loading) {
        return (
            <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                <div className="bg-white rounded-2xl p-8 flex flex-col items-center gap-4 shadow-2xl">
                    <LogoLoader className="w-10 h-10 animate-spin text-indigo-500" />
                    <p className="text-gray-600 font-medium">Fetching AI Summary...</p>
                </div>
            </div>
        );
    }

    if (!summary) return null;

    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
                {/* Header */}
                <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-gradient-to-r from-indigo-500 to-purple-600 text-white">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur-md flex items-center justify-center">
                            <Sparkles className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold">AI Meeting Insights</h2>
                            <p className="text-xs text-indigo-100 opacity-90">Generated by Gemini Pro</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="w-8 h-8 rounded-full hover:bg-white/20 flex items-center justify-center transition-colors">
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Body */}
                <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-gray-50/50">

                    {/* Summary Header */}
                    <div className="space-y-2">
                        <h3 className="text-2xl font-black text-gray-900 leading-tight">{summary.title}</h3>
                        <div className="flex flex-wrap gap-2">
                            <span className="px-2 py-1 rounded-md bg-indigo-100 text-indigo-700 text-[10px] font-bold uppercase tracking-wider">
                                {summary.meetingDate}
                            </span>
                            <span className="px-2 py-1 rounded-md bg-gray-100 text-gray-600 text-[10px] font-bold uppercase tracking-wider">
                                {summary.participants?.length || 0} Participants
                            </span>
                        </div>
                    </div>

                    {/* Quick Wrap-up */}
                    <div className="p-5 rounded-2xl bg-white shadow-sm border border-gray-100">
                        <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800 mb-3">
                            <FileText className="w-4 h-4 text-indigo-500" />
                            Executive Summary
                        </h4>
                        <div className="space-y-4">
                            <div>
                                <h5 className="text-[11px] font-black text-indigo-500 uppercase tracking-widest mb-1">The Goal</h5>
                                <p className="text-sm text-gray-600 leading-relaxed font-medium">{summary.summary?.agenda}</p>
                            </div>
                            <div>
                                <h5 className="text-[11px] font-black text-purple-500 uppercase tracking-widest mb-1">Key Highlights</h5>
                                <p className="text-sm text-gray-600 leading-relaxed">{summary.summary?.highlights}</p>
                            </div>
                        </div>
                    </div>

                    {/* Decisions & Action Items */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Decisions */}
                        <div className="space-y-4">
                            <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800">
                                <CheckCircle className="w-4 h-4 text-emerald-500" />
                                Key Decisions
                            </h4>
                            <div className="space-y-2">
                                {summary.summary?.decisions?.map((decision: string, i: number) => (
                                    <div key={i} className="p-3 rounded-xl bg-emerald-50 border border-emerald-100 text-sm text-emerald-800 font-medium">
                                        {decision}
                                    </div>
                                ))}
                                {(!summary.summary?.decisions || summary.summary.decisions.length === 0) && (
                                    <p className="text-xs text-gray-400 italic">No formal decisions recorded.</p>
                                )}
                            </div>
                        </div>

                        {/* Action Items */}
                        <div className="space-y-4">
                            <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800">
                                <Target className="w-4 h-4 text-rose-500" />
                                Action Items
                            </h4>
                            <div className="space-y-2">
                                {summary.actionItems?.map((item: any, i: number) => (
                                    <div key={i} className="p-3 rounded-xl bg-white border border-gray-100 shadow-sm flex items-start gap-3">
                                        <div className="w-5 h-5 rounded-full bg-rose-50 flex items-center justify-center text-[10px] font-bold text-rose-500 mt-0.5">
                                            {i + 1}
                                        </div>
                                        <div className="min-w-0 flex-1">
                                            <p className="text-sm text-gray-800 font-medium leading-tight">{item.task}</p>
                                            <div className="flex items-center gap-2 mt-1.5">
                                                <span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-100 text-gray-500 font-bold uppercase">
                                                    {item.assignee || 'Unassigned'}
                                                </span>
                                                {item.dueDate && (
                                                    <span className="text-[10px] text-rose-400 font-bold">
                                                        Due: {item.dueDate}
                                                    </span>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                ))}
                                {(!summary.actionItems || summary.actionItems.length === 0) && (
                                    <p className="text-xs text-gray-400 italic">No specific tasks extracted.</p>
                                )}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="px-6 py-4 border-t border-gray-100 bg-white flex items-center justify-between">
                    <p className="text-xs text-gray-400 italic">
                        All notes stored in Google Sheets ID: {summary.spreadsheetId?.slice(0, 10)}...
                    </p>
                    <div className="flex gap-2">
                        <button
                            onClick={() => window.open(`https://docs.google.com/spreadsheets/d/${summary.spreadsheetId}`, '_blank')}
                            className="btn-secondary text-[11px] px-3 py-1.5 h-auto flex items-center gap-1.5"
                        >
                            <ExternalLink className="w-3.5 h-3.5" /> Google Sheets
                        </button>
                        <button onClick={onClose} className="btn-primary text-[11px] px-4 py-1.5 h-auto">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
