import { prisma } from '@workspace/db';
import { AICompanyConfigService, aiProviderService } from '@workspace/ai';

/**
 * Project analytics and brand-voice content ideas for the Social Studio (web + mobile).
 *
 * Analytics are computed ONLY from this platform's own records (posts, review sessions, inbox conversations) for one
 * company + project. Nothing is estimated or invented: audience/engagement numbers from the social networks are not
 * stored here, so they are not reported.
 *
 * Ideas are generated by the workspace's configured AI provider, grounded in the project's saved brand voice. With no
 * provider configured the caller gets a clear error, never canned ideas.
 */

export class SocialInsightsError extends Error {
    constructor(public status: number, public code: string, message: string) {
        super(message);
    }
}

export const ANALYTICS_RANGES: Record<string, number> = { '7d': 7, '30d': 30, '90d': 90 };

/** Minimal Prisma surface used here, so tests can pass an in-memory stand-in. */
export interface InsightsDb {
    project: { findFirst: (args: any) => Promise<any> };
    socialPost: { count: (args: any) => Promise<number>; findMany: (args: any) => Promise<any[]> };
    clientReviewSession: { findMany: (args: any) => Promise<any[]> };
    socialConversation: { count: (args: any) => Promise<number> };
    brandVoiceProfile: { findFirst: (args: any) => Promise<any> };
    socialEngagementRule?: { count: (args: any) => Promise<number> };
    socialInteractionLog?: { count: (args: any) => Promise<number> };
}

const defaultDb = () => prisma as unknown as InsightsDb;

async function findSocialProject(db: InsightsDb, projectId: string, companyId: string) {
    if (!companyId) throw new SocialInsightsError(401, 'COMPANY_REQUIRED', 'Company context required');
    const project = await db.project.findFirst({
        where: { id: projectId, companyId, projectType: 'social_media', deletedAt: null },
        select: { id: true, name: true, description: true, socialServices: true },
    });
    if (!project) throw new SocialInsightsError(404, 'PROJECT_NOT_FOUND', 'Project not found');
    return project;
}

const round1 = (n: number) => Math.round(n * 10) / 10;
const platformKey = (p: string) => String(p || 'unknown').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || 'unknown';

/**
 * Flat numeric metrics for one project over the last `range` (7d | 30d | 90d).
 * Tenant-scoped: every query filters on companyId AND projectId; an unknown / foreign project is a 404.
 */
export async function getProjectAnalytics(params: { projectId: string; companyId: string; range?: string; now?: Date }, db: InsightsDb = defaultDb()) {
    const range = params.range && ANALYTICS_RANGES[params.range] ? params.range : '30d';
    if (params.range && !ANALYTICS_RANGES[params.range]) {
        throw new SocialInsightsError(400, 'INVALID_RANGE', `range must be one of ${Object.keys(ANALYTICS_RANGES).join(', ')}`);
    }
    const days = ANALYTICS_RANGES[range];
    const { projectId, companyId } = params;
    await findSocialProject(db, projectId, companyId);

    const now = params.now || new Date();
    const since = new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
    const scope = { companyId, projectId };

    const [
        postsCreated,
        postsPublished,
        postsScheduledInRange,
        postsScheduledUpcoming,
        postsFailed,
        postsAwaitingApproval,
        publishedRows,
        sessions,
        inboxConversations,
        inboxUnread,
        inboxConvertedToLeads,
        engagementRulesCount,
        engagementInteractionsCount,
    ] = await Promise.all([
        db.socialPost.count({ where: { ...scope, createdAt: { gte: since, lte: now } } }),
        db.socialPost.count({ where: { ...scope, status: 'published', publishedAt: { gte: since, lte: now } } }),
        db.socialPost.count({ where: { ...scope, status: { in: ['scheduled', 'approved'] }, scheduledFor: { gte: since, lte: now } } }),
        db.socialPost.count({ where: { ...scope, status: { in: ['scheduled', 'approved'] }, scheduledFor: { gt: now } } }),
        db.socialPost.count({ where: { ...scope, status: 'failed', updatedAt: { gte: since, lte: now } } }),
        db.socialPost.count({ where: { ...scope, status: { in: ['in_review', 'pending_review'] } } }),
        db.socialPost.findMany({
            where: { ...scope, status: 'published', publishedAt: { gte: since, lte: now } },
            select: { socialAccount: { select: { platform: true } }, variants: { select: { platform: true } } },
        }),
        db.clientReviewSession.findMany({
            where: { ...scope, createdAt: { gte: since, lte: now } },
            select: { status: true, createdAt: true, updatedAt: true },
        }),
        db.socialConversation.count({ where: { ...scope, lastMessageAt: { gte: since, lte: now } } }),
        db.socialConversation.count({ where: { ...scope, lastMessageAt: { gte: since, lte: now }, isRead: false } }),
        db.socialConversation.count({ where: { ...scope, lastMessageAt: { gte: since, lte: now }, convertedLeadId: { not: null } } }),
        db.socialEngagementRule?.count ? db.socialEngagementRule.count({ where: { companyId, projectId, status: 'active' } }).catch(() => 0) : Promise.resolve(0),
        db.socialInteractionLog?.count ? db.socialInteractionLog.count({ where: { companyId, createdAt: { gte: since, lte: now } } }).catch(() => 0) : Promise.resolve(0),
    ]);

    const analytics: Record<string, number | string> = {
        range,
        rangeDays: days,
        postsCreated,
        postsPublished,
        postsScheduledInRange,
        postsScheduledUpcoming,
        postsFailed,
        postsAwaitingApproval,
        engagementActiveRules: engagementRulesCount,
        engagementInteractionsInRange: engagementInteractionsCount,
    };

    // By platform: the connected account's platform, else the platform variants the post was published with.
    const byPlatform: Record<string, number> = {};
    for (const row of publishedRows) {
        const platforms = row.socialAccount?.platform
            ? [row.socialAccount.platform]
            : Array.from(new Set((row.variants || []).map((v: any) => v.platform).filter(Boolean)));
        for (const p of platforms.length ? platforms : ['unknown']) {
            const key = `published_${platformKey(p as string)}`;
            byPlatform[key] = (byPlatform[key] || 0) + 1;
        }
    }
    Object.assign(analytics, Object.fromEntries(Object.entries(byPlatform).sort(([a], [b]) => a.localeCompare(b))));

    // Approval turnaround: sessions the client approved; approval time is the session's last update.
    const approved = sessions.filter((s) => s.status === 'approved');
    analytics.reviewSessionsSent = sessions.length;
    analytics.reviewSessionsApproved = approved.length;
    analytics.reviewSessionsRevisionsRequested = sessions.filter((s) => s.status === 'revisions_requested').length;
    analytics.reviewSessionsPending = sessions.filter((s) => s.status === 'pending' || s.status === 'partially_approved').length;
    if (approved.length) {
        const hours = approved.map((s) => Math.max(0, new Date(s.updatedAt).getTime() - new Date(s.createdAt).getTime()) / 3_600_000);
        analytics.approvalTurnaroundHoursAvg = round1(hours.reduce((a, b) => a + b, 0) / hours.length);
        const sorted = [...hours].sort((a, b) => a - b);
        const mid = Math.floor(sorted.length / 2);
        analytics.approvalTurnaroundHoursMedian = round1(sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2);
    }

    analytics.inboxConversations = inboxConversations;
    analytics.inboxUnread = inboxUnread;
    analytics.inboxConvertedToLeads = inboxConvertedToLeads;

    return analytics;
}

// ── content ideas ─────────────────────────────────────────────────────────────────────────────────────────────

export interface ContentIdea {
    title: string;
    hook: string;
    caption: string;
    platform: string;
    pillar: string;
}

export interface IdeasAi {
    generate: (prompt: string, options?: any) => Promise<string>;
}

/** The company's configured LLM client (same resolution as the rest of the platform's AI features), or null. */
async function companyAiClient(companyId: string): Promise<IdeasAi | null> {
    const { settings } = await AICompanyConfigService.getCompanyAISettings(companyId);
    return aiProviderService.getClient(settings);
}

export const MAX_IDEAS = 10;

function buildIdeasPrompt(project: any, voice: any, count: number, platforms: string[]) {
    const list = (v: any) => (Array.isArray(v) && v.length ? v.join(', ') : 'none');
    const samples = Array.isArray(voice.sampleViralPosts) ? voice.sampleViralPosts.slice(0, 5).map((s: string) => `- ${String(s).slice(0, 500)}`).join('\n') : '';
    return `You are a social media strategist. Propose ${count} distinct content ideas for the brand below.

PROJECT: ${project.name}${project.description ? `\nABOUT: ${String(project.description).slice(0, 1000)}` : ''}
BRAND TONE: ${voice.tone}
TARGET AUDIENCE: ${voice.targetAudience}
PLATFORMS: ${platforms.length ? platforms.join(', ') : 'choose the best fit per idea'}
DEFAULT HASHTAGS: ${list(voice.defaultHashtags)}
STANDARD CTAS: ${list(voice.standardCtas)}
NEVER USE THESE WORDS: ${list(voice.forbiddenWords)}
${samples ? `POSTS THAT PERFORMED WELL (match their voice):\n${samples}\n` : ''}
Return ONLY a JSON array (no markdown) of exactly ${count} objects:
[{"title": "...", "hook": "first line that stops the scroll", "caption": "full ready-to-post caption", "platform": "instagram|linkedin|tiktok|youtube|facebook", "pillar": "educational|promotional|community|behind_the_scenes|entertainment"}]`;
}

function parseIdeas(raw: string, count: number, forbidden: string[]): ContentIdea[] {
    let text = String(raw || '').trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
    const start = text.indexOf('[');
    const end = text.lastIndexOf(']');
    if (start >= 0 && end > start) text = text.slice(start, end + 1);
    let parsed: any;
    try {
        parsed = JSON.parse(text);
    } catch {
        return [];
    }
    if (!Array.isArray(parsed)) return [];
    const banned = forbidden.map((w) => String(w).toLowerCase()).filter(Boolean);
    const str = (v: any) => (typeof v === 'string' ? v.trim() : '');
    return parsed
        .map((i: any) => ({
            title: str(i?.title || i?.headline),
            hook: str(i?.hook),
            caption: str(i?.caption || i?.content),
            platform: str(i?.platform).toLowerCase(),
            pillar: str(i?.pillar),
        }))
        .filter((i) => i.title && !banned.some((w) => `${i.title} ${i.hook} ${i.caption}`.toLowerCase().includes(w)))
        .slice(0, count);
}

/**
 * Content ideas grounded in the project's SAVED brand voice. Errors (SocialInsightsError):
 * 404 PROJECT_NOT_FOUND, 409 BRAND_VOICE_NOT_CONFIGURED, 503 AI_NOT_CONFIGURED, 502 AI_PROVIDER_ERROR / AI_BAD_RESPONSE.
 */
export async function generateContentIdeas(
    params: { projectId: string; companyId: string; count?: number },
    deps: { db?: InsightsDb; ai?: (companyId: string) => Promise<IdeasAi | null> } = {}
): Promise<ContentIdea[]> {
    const db = deps.db || defaultDb();
    const count = Math.min(MAX_IDEAS, Math.max(1, Math.floor(Number(params.count) || 3)));
    const project = await findSocialProject(db, params.projectId, params.companyId);

    const voice = await db.brandVoiceProfile.findFirst({ where: { companyId: params.companyId, projectId: params.projectId } });
    if (!voice) {
        throw new SocialInsightsError(409, 'BRAND_VOICE_NOT_CONFIGURED', 'Save a brand voice for this project first; ideas are generated from it.');
    }

    let ai: IdeasAi | null;
    try {
        ai = await (deps.ai || companyAiClient)(params.companyId);
    } catch (err: any) {
        console.error('[SocialInsights] AI settings could not be resolved:', err?.message);
        ai = null;
    }
    if (!ai) {
        throw new SocialInsightsError(503, 'AI_NOT_CONFIGURED', 'No AI provider is configured for this workspace. Add one in Settings > AI.');
    }

    const platforms = await db.socialPost
        .findMany({ where: { companyId: params.companyId, projectId: params.projectId, socialAccountId: { not: null } }, select: { socialAccount: { select: { platform: true } } }, take: 200 })
        .then((rows) => Array.from(new Set(rows.map((r: any) => r.socialAccount?.platform).filter(Boolean))) as string[])
        .catch(() => [] as string[]);

    let raw: string;
    try {
        raw = await ai.generate(buildIdeasPrompt(project, voice, count, platforms), { max_tokens: 3000 });
    } catch (err: any) {
        console.error('[SocialInsights] AI provider call failed:', err?.message);
        throw new SocialInsightsError(502, 'AI_PROVIDER_ERROR', 'The AI provider could not generate ideas. Check the workspace AI settings and try again.');
    }
    const ideas = parseIdeas(raw, count, voice.forbiddenWords || []);
    if (!ideas.length) {
        throw new SocialInsightsError(502, 'AI_BAD_RESPONSE', 'The AI provider returned no usable ideas. Please try again.');
    }
    return ideas;
}

export type MetricsSource = 'live' | 'stored' | 'unavailable';

export interface LivePlatformMetric {
    socialAccountId: string;
    platform: string;
    platformAccountId: string;
    accountName: string;
    /** live = fetched from the network just now; stored = our last saved value (see fetchedAt); unavailable = see `unavailable`. */
    source: MetricsSource;
    /** When these numbers were fetched (live) or last saved (stored). */
    fetchedAt: string | null;
    /** null = not reported by the platform / not available. Never estimated. */
    followersCount: number | null;
    reach: number | null;
    impressions: number | null;
    engagements: number | null;
    views: number | null;
    periodDays: number | null;
    unavailable?: { code: 'PLATFORM_METRICS_UNAVAILABLE'; reason: 'missing_token' | 'missing_scope' | 'app_review' | 'timeout' | 'provider_error' | 'unsupported'; message: string };
}

const METRICS_PERIOD_DAYS = 28;

function unavailableFrom(err: any): LivePlatformMetric['unavailable'] {
    const code = err?.code;
    const msg = String(err?.message || err).slice(0, 300);
    const http = err?.details?.httpStatus;
    let reason: NonNullable<LivePlatformMetric['unavailable']>['reason'] = 'provider_error';
    if (code === 'REAUTH_REQUIRED') reason = 'missing_token';
    else if (code === 'PROVIDER_TIMEOUT') reason = 'timeout';
    else if (http === 403 || /permission|scope|insufficient/i.test(msg)) reason = /review|advanced access/i.test(msg) ? 'app_review' : 'missing_scope';
    return { code: 'PLATFORM_METRICS_UNAVAILABLE', reason, message: msg };
}

async function getJson(platform: string, url: string, token: string, what: string) {
    const { providerFetch, expectOk } = require('./publishing/http');
    const res = await providerFetch(platform, url, { headers: { Authorization: `Bearer ${token}` }, timeoutMs: 10_000 });
    return expectOk(platform, res, what);
}

const sumInsight = (data: any[], name: string): number | null => {
    const row = (data || []).find((d: any) => d?.name === name);
    if (!row) return null;
    if (row.total_value && typeof row.total_value.value === 'number') return row.total_value.value;
    const vals = (row.values || []).map((v: any) => Number(v?.value)).filter((n: number) => Number.isFinite(n));
    return vals.length ? vals[vals.length - 1] : null;
};

/**
 * Account metrics for a project's connected accounts, read from the networks with the vault token:
 * Instagram (Graph /insights), Facebook Pages (Graph /insights), YouTube (Data API channel statistics).
 * Other platforms return the stored follower count labelled `stored` with its timestamp. Nothing is estimated:
 * a missing token / scope / app review is reported per account as PLATFORM_METRICS_UNAVAILABLE.
 */
export async function fetchLivePlatformMetrics(params: { projectId: string; companyId: string }): Promise<LivePlatformMetric[]> {
    const { projectId, companyId } = params;
    if (!companyId) throw new SocialInsightsError(401, 'COMPANY_REQUIRED', 'Company context required');
    const { getDb } = require('./publishing/http');
    const { SocialTokenVault } = require('./publishing/token-vault');
    const { META_GRAPH_VERSION } = require('./publishing/config');
    const db = getDb();
    const project = await db.project.findFirst({ where: { id: projectId, companyId }, select: { id: true } });
    if (!project) throw new SocialInsightsError(404, 'PROJECT_NOT_FOUND', 'Project not found');

    const accounts = await db.socialAccount.findMany({
        where: { companyId, projectId, isActive: true },
        select: { id: true, companyId: true, platform: true, platformAccountId: true, accountName: true, followersCount: true, reauthRequired: true, updatedAt: true },
    });
    const graph = (p: string) => `https://graph.facebook.com/${META_GRAPH_VERSION()}/${p}`;
    const now = new Date();
    const since = Math.floor((now.getTime() - METRICS_PERIOD_DAYS * 86_400_000) / 1000);
    const until = Math.floor(now.getTime() / 1000);

    return Promise.all(
        accounts.map(async (acc: any): Promise<LivePlatformMetric> => {
            const base: LivePlatformMetric = {
                socialAccountId: acc.id,
                platform: acc.platform,
                platformAccountId: acc.platformAccountId,
                accountName: acc.accountName || acc.platform,
                source: 'stored',
                fetchedAt: acc.updatedAt ? new Date(acc.updatedAt).toISOString() : null,
                followersCount: typeof acc.followersCount === 'number' ? acc.followersCount : null,
                reach: null,
                impressions: null,
                engagements: null,
                views: null,
                periodDays: null,
            };
            const platform = String(acc.platform).toLowerCase();
            if (!['instagram', 'facebook', 'youtube'].includes(platform)) {
                return { ...base, unavailable: { code: 'PLATFORM_METRICS_UNAVAILABLE', reason: 'unsupported', message: `Live metrics are not available for ${acc.platform}; showing the stored follower count.` } };
            }
            try {
                const token = await SocialTokenVault.getAccessToken(acc);
                const id = encodeURIComponent(acc.platformAccountId);
                if (platform === 'instagram') {
                    const profile = await getJson('instagram', graph(`${id}?fields=followers_count`), token, 'Instagram profile');
                    const ins = await getJson('instagram', graph(`${id}/insights?metric=reach,views,accounts_engaged,total_interactions&period=day&metric_type=total_value&since=${since}&until=${until}`), token, 'Instagram insights');
                    return { ...base, source: 'live', fetchedAt: now.toISOString(), followersCount: profile.followers_count ?? null, reach: sumInsight(ins.data, 'reach'), views: sumInsight(ins.data, 'views'), engagements: sumInsight(ins.data, 'total_interactions'), periodDays: METRICS_PERIOD_DAYS };
                }
                if (platform === 'facebook') {
                    const page = await getJson('facebook', graph(`${id}?fields=followers_count,fan_count`), token, 'Facebook page');
                    const ins = await getJson('facebook', graph(`${id}/insights?metric=page_impressions_unique,page_post_engagements&period=days_28`), token, 'Facebook page insights');
                    return { ...base, source: 'live', fetchedAt: now.toISOString(), followersCount: page.followers_count ?? page.fan_count ?? null, reach: sumInsight(ins.data, 'page_impressions_unique'), engagements: sumInsight(ins.data, 'page_post_engagements'), periodDays: METRICS_PERIOD_DAYS };
                }
                const ch = await getJson('youtube', 'https://www.googleapis.com/youtube/v3/channels?part=statistics&mine=true', token, 'YouTube channel statistics');
                const stats = ch.items?.[0]?.statistics;
                if (!stats) throw Object.assign(new Error('YouTube returned no channel for this token'), { code: 'PROVIDER_ERROR' });
                return {
                    ...base,
                    source: 'live',
                    fetchedAt: now.toISOString(),
                    followersCount: stats.hiddenSubscriberCount ? null : Number(stats.subscriberCount ?? NaN) || (stats.subscriberCount === '0' ? 0 : null),
                    views: stats.viewCount != null ? Number(stats.viewCount) : null,
                    periodDays: null, // lifetime channel totals
                };
            } catch (err: any) {
                return { ...base, unavailable: unavailableFrom(err) };
            }
        }),
    );
}
