import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 180 Documentation Sidebar Configuration
 * Autogenerates the complete hierarchical sidebar for all 180workspace architecture,
 * engineering runbooks, database schemas, and API references.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
