'use client';

import { LogoLoader } from "@workspace/ui";
import { useState, useEffect } from 'react';
import { X, FileText, CheckCircle, Target, Sparkles, Download, ExternalLink } from 'lucide-react';
import api from '@/lib/api';
import toast from 'react-hot-toast';
import clsx from 'clsx';
import { PlatformModal } from '@/components/shared/PlatformModal';

interface MeetingSummaryModalProps {
    roomId: string;
    onClose: () => void;
}

export default function MeetingSummaryModal({ roomId, onClose }: MeetingSummaryModalProps) {
    const [summary, setSummary] = useState<any>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchSummary = async () => {
            try {
                const { data } = await api.get(`/api/meeting/ai/summary/${roomId}`);
                setSummary(data.summary);
            } catch (err) {
                console.error('Failed to fetch summary:', err);
                toast.error('Could not find AI summary for this meeting.');
                onClose();
            } finally {
                setLoading(false);
            }
        };

        fetchSummary();
    }, [roomId, onClose]);

    if (loading) {
        return (
            <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                <div className="bg-white rounded-2xl p-8 flex flex-col items-center gap-4 shadow-2xl">
                    <LogoLoader className="w-10 h-10 animate-spin text-indigo-500" />
                    <p className="text-gray-600 font-medium">Fetching AI Summary...</p>
                </div>
            </div>
        );
    }

    if (!summary) return null;

    return (
        <PlatformModal
            isOpen={true}
            onClose={onClose}
            title="AI Meeting Insights"
            icon={Sparkles}
            iconBgClass="bg-indigo-100"
            iconColorClass="text-indigo-600"
            maxWidthClass="max-w-3xl"
            footer={
                <>
                    <button
                        onClick={() => window.open(`https://docs.google.com/spreadsheets/d/${summary.spreadsheetId}`, '_blank')}
                        className="btn-secondary flex items-center gap-2"
                    >
                        <ExternalLink className="w-4 h-4" /> Google Sheets
                    </button>
                    <button onClick={onClose} className="btn-primary">
                        Close
                    </button>
                </>
            }
            subHeader={
                <div className="px-6 py-2 border-b border-gray-100 bg-gray-50 flex items-center justify-between">
                    <p className="text-xs text-gray-500 italic font-medium">Generated by Gemini Pro</p>
                    <p className="text-[10px] text-gray-400 font-mono">
                        Sheet ID: {summary.spreadsheetId?.slice(0, 10)}...
                    </p>
                </div>
            }
        >
            <div className="space-y-8">
                {/* Summary Header */}
                <div className="space-y-2">
                    <h3 className="text-2xl font-black text-gray-900 leading-tight">{summary.title}</h3>
                    <div className="flex flex-wrap gap-2">
                        <span className="badge-purple">
                            {summary.meetingDate}
                        </span>
                        <span className="badge-gray">
                            {summary.participants?.length || 0} Participants
                        </span>
                    </div>
                </div>

                {/* Quick Wrap-up */}
                <div className="card shadow-none">
                    <div className="card-header border-b-0 pb-2">
                        <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800">
                            <FileText className="w-4 h-4 text-indigo-500" />
                            Executive Summary
                        </h4>
                    </div>
                    <div className="card-body space-y-4 pt-0">
                        <div>
                            <h5 className="text-[11px] font-black text-indigo-500 uppercase tracking-widest mb-1">The Goal</h5>
                            <p className="text-sm text-gray-600 leading-relaxed font-medium">{summary.summary?.agenda}</p>
                        </div>
                        <div>
                            <h5 className="text-[11px] font-black text-purple-500 uppercase tracking-widest mb-1">Key Highlights</h5>
                            <p className="text-sm text-gray-600 leading-relaxed">{summary.summary?.highlights}</p>
                        </div>
                    </div>
                </div>

                {/* Decisions & Action Items */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Decisions */}
                    <div className="space-y-4">
                        <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800">
                            <CheckCircle className="w-4 h-4 text-emerald-500" />
                            Key Decisions
                        </h4>
                        <div className="space-y-2">
                            {summary.summary?.decisions?.map((decision: string, i: number) => (
                                <div key={i} className="p-3 rounded-xl bg-emerald-50 border border-emerald-100 text-sm text-emerald-800 font-medium">
                                    {decision}
                                </div>
                            ))}
                            {(!summary.summary?.decisions || summary.summary.decisions.length === 0) && (
                                <p className="text-xs text-gray-400 italic">No formal decisions recorded.</p>
                            )}
                        </div>
                    </div>

                    {/* Action Items */}
                    <div className="space-y-4">
                        <h4 className="flex items-center gap-2 text-sm font-bold text-gray-800">
                            <Target className="w-4 h-4 text-rose-500" />
                            Action Items
                        </h4>
                        <div className="space-y-2">
                            {summary.actionItems?.map((item: any, i: number) => (
                                <div key={i} className="p-3 rounded-xl bg-white border border-gray-100 shadow-sm flex items-start gap-3">
                                    <div className="w-5 h-5 rounded-full bg-rose-50 flex items-center justify-center text-[10px] font-bold text-rose-500 mt-0.5">
                                        {i + 1}
                                    </div>
                                    <div className="min-w-0 flex-1">
                                        <p className="text-sm text-gray-800 font-medium leading-tight">{item.task}</p>
                                        <div className="flex items-center gap-2 mt-1.5">
                                            <span className="text-[10px] px-1.5 py-0.5 rounded bg-gray-100 text-gray-500 font-bold uppercase">
                                                {item.assignee || 'Unassigned'}
                                            </span>
                                            {item.dueDate && (
                                                <span className="text-[10px] text-rose-400 font-bold">
                                                    Due: {item.dueDate}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            ))}
                            {(!summary.actionItems || summary.actionItems.length === 0) && (
                                <p className="text-xs text-gray-400 italic">No specific tasks extracted.</p>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </PlatformModal>
    );
}
