'use client';

import { Sparkles, Bot, Terminal, Cpu, Copy } from 'lucide-react';
import toast from 'react-hot-toast';
import { Drawer } from "@/components/ui/Drawer";

interface AiAgentGuideDrawerProps {
    apiKey: string;
    origin: string;
    onClose: () => void;
    open: boolean;
}

export default function AiAgentGuideDrawer({ apiKey, origin, onClose, open }: AiAgentGuideDrawerProps) {
    const prompt = `I want to integrate a dynamic job board into my existing website. 
Please create a high-fidelity, responsive React or HTML/Tailwind component that fetches data from my 180workspace Job API.

API CONFIGURATION:
- Endpoint: GET ${origin}/api/public/jobs
- Method: GET
- Authentication: Header 'x-api-key' with value \`${apiKey || 'YOUR_API_KEY'}\`

SECURITY NOTE (Domain Whitelisting):
- For browser-based requests, you MUST ensure your website domain (e.g., yourcompany.com) is added to the "Whitelisted Domains" in the 180workspace Recruitment Dashboard -> API Settings.
- Requests from unauthorized origins will return a 403 Forbidden error.

UI REQUIREMENTS:
1. Fetch jobs on component mount.
2. Display job listings in a modern card layout or clean list.
3. Show Title, Department, Location, and Job Type (e.g., Full-time, Remote).
4. Include a 'View Details & Apply' button for each job.
5. The application link should point to: ${origin}/jobs/apply/{jobId}
6. Add professional loading states and handle 'No Jobs Found' scenarios.

Please provide the complete, production-ready code with integrated styling. Ensure it looks premium and matches a professional corporate aesthetic.`;

    const copyPrompt = () => {
        navigator.clipboard.writeText(prompt);
        toast.success('AI Prompt copied to clipboard!');
    };

    return (
        <Drawer 
            open={open} 
            onClose={onClose} 
            title="AI Agent Bridge"
            icon={<Sparkles className="w-5 h-5 text-indigo-600" />}
            size="md"
        >
            <div className="flex flex-col h-full bg-white relative">
                <div className="absolute top-0 right-0 p-8 opacity-5 pointer-events-none">
                    <Cpu className="w-32 h-32 text-indigo-900" />
                </div>
                
                <div className="flex-1 overflow-y-auto p-6 custom-scrollbar space-y-6 relative z-10">
                    <div className="text-sm text-gray-500 font-medium">Auto-integrate your Job Portal in seconds</div>
                    {/* Steps */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        {[
                            { icon: <Copy className="w-4 h-4" />, title: 'Copy Prompt', desc: 'Click the button below to copy the AI instruction.' },
                            { icon: <Bot className="w-4 h-4" />, title: 'Paste to AI', desc: 'Paste it into ChatGPT, Claude, or any AI Agent.' },
                            { icon: <Terminal className="w-4 h-4" />, title: 'Deploy Code', desc: 'Copy the code generated by AI into your website.' }
                        ].map((s, i) => (
                            <div key={i} className="p-4 rounded-2xl bg-gray-50 border border-gray-100 flex flex-col items-center text-center">
                                <div className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center text-indigo-600 mb-3 border border-gray-100">
                                    {s.icon}
                                </div>
                                <h4 className="text-xs font-bold text-gray-900 mb-1">{s.title}</h4>
                                <p className="text-[10px] text-gray-500 leading-relaxed font-medium">{s.desc}</p>
                            </div>
                        ))}
                    </div>

                    {/* Prompt Preview */}
                    <div className="space-y-3">
                        <div className="flex items-center justify-between px-1">
                            <h4 className="text-xs font-bold text-indigo-900 uppercase tracking-widest flex items-center gap-2">
                                <Terminal className="w-3 h-3" /> Ready-Made Prompt
                            </h4>
                        </div>
                        <div className="relative group">
                            <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-2xl blur opacity-10 group-hover:opacity-20 transition duration-1000"></div>
                            <div className="relative bg-gray-900 rounded-2xl p-5 font-mono text-[11px] text-gray-300 leading-relaxed border border-gray-800 shadow-xl max-h-[250px] overflow-y-auto custom-scrollbar whitespace-pre-wrap">
                                {prompt}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Footer Action */}
                <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-3">
                    <p className="text-xs text-gray-400 font-medium italic select-none">
                        Variables (API Key, URLs) are pre-configured
                    </p>
                    <button 
                        onClick={copyPrompt}
                        className="btn-primary w-full sm:w-auto"
                    >
                        <Copy className="w-4 h-4 mr-2" /> Copy Prompt for AI
                    </button>
                </div>
            </div>
        </Drawer>
    );
}
