// @ts-nocheck
import { prisma } from '@workspace/db';
import { ResourceDefinition } from '../control-plane/types/resource.types';
import { AIToolDefinition } from '../tools/ai-tool-registry';

/**
 * Voiceforce Agent Request Resource Definition
 */
export const agentRequestResource: ResourceDefinition = {
    kind: 'agent_request',
    domain: 'voiceforce',
    description: 'Incoming customer meeting bookings and triage requests generated by Voiceforce AI voice agents.',
    allowedRoles: ['admin', 'employee'],
    requiredPermissions: ['calendar:create', 'calendar:all'],
    schema: {
        identityKeys: ['id', 'companyId'],
        stateFields: {
            customerName: 'string',
            customerPhone: 'string',
            topic: 'string',
            status: 'string',
            scheduledStart: 'date'
        }
    },
    capabilities: {
        read: async (query, context) => {
            const { companyId } = context;
            const filterStatus = query.statusFilter || query.status || 'all';

            const whereClause: any = { companyId };
            if (filterStatus !== 'all') {
                whereClause.status = filterStatus;
            }

            const [requests, counts] = await Promise.all([
                (prisma as any).agentRequest ? (prisma as any).agentRequest.findMany({
                    where: whereClause,
                    orderBy: { createdAt: 'desc' },
                    take: query.limit || 10,
                    include: { calendarEvent: true }
                }).catch(() => []) : [],
                (prisma as any).agentRequest ? Promise.all([
                    (prisma as any).agentRequest.count({ where: { companyId, status: 'pending_review' } }).catch(() => 0),
                    (prisma as any).agentRequest.count({ where: { companyId, status: 'auto_scheduled' } }).catch(() => 0),
                    (prisma as any).agentRequest.count({ where: { companyId, status: 'confirmed' } }).catch(() => 0)
                ]) : [0, 0, 0]
            ]);

            const [pendingCount, autoScheduledCount, confirmedCount] = counts;
            const requestList = requests.map((r: any) => {
                const timeStr = r.scheduledStart ? new Date(r.scheduledStart).toLocaleString() : (r.requestedTimeRaw || 'Time TBD');
                return `- **${r.customerName}** (${r.customerPhone || r.customerEmail || 'No contact'})\n  • Topic: *${r.topic}*\n  • Scheduled: \`${timeStr}\`\n  • Status: \`${r.status}\` | ID: \`${r.id}\``;
            }).join('\n\n');

            const message = `📋 **Voiceforce Agent Request Queue**\n\n` +
                `• **Pending Review:** ${pendingCount}\n` +
                `• **Auto-Scheduled:** ${autoScheduledCount}\n` +
                `• **Confirmed:** ${confirmedCount}\n\n` +
                (requestList || 'No agent requests found for this filter.') +
                `\n\n👉 [Manage Agent Requests in Orbit AI](/ai)`;

            return {
                success: true,
                total: requests.length,
                pendingCount,
                autoScheduledCount,
                confirmedCount,
                requests,
                message
            };
        }
    }
};

// ==========================================
// Backward-Compatible Tool Adapters
// ==========================================

export const listAgentRequestsTool: AIToolDefinition = {
    name: 'list_agent_requests',
    description: 'Lists pending, scheduled, and confirmed customer meeting requests created by Voiceforce AI agents.',
    allowedRoles: ['admin', 'employee'],
    requiredPermissions: ['calendar:view', 'calendar:all'],
    category: 'voiceforce',
    parameters: {
        statusFilter: { type: 'string', description: 'Filter: all, pending_review, auto_scheduled, confirmed, rejected' },
        limit: { type: 'number', description: 'Max items to return (default: 10)' }
    },
    execute: (args, context) => agentRequestResource.capabilities.read!(args, context)
};

export const processAgentRequestTool: AIToolDefinition = {
    name: 'process_agent_request',
    description: 'Approves, confirms, reschedules, or rejects an incoming Voiceforce agent meeting request.',
    allowedRoles: ['admin', 'employee'],
    requiredPermissions: ['calendar:create', 'calendar:all'],
    category: 'voiceforce',
    parameters: {
        requestId: { type: 'string', description: 'UUID of the AgentRequest ticket', required: true },
        action: { type: 'string', description: 'Action: approve, confirm, reschedule, or reject', required: true },
        newTime: { type: 'string', description: 'New time if action is reschedule' },
        notes: { type: 'string', description: 'Resolution notes' }
    },
    execute: async (args, context) => {
        const { companyId, userId } = context;
        if (!companyId) return { error: 'Company ID is required' };
        if (!args.requestId) return { error: 'requestId is required' };

        const request = await (prisma as any).agentRequest.findFirst({
            where: { id: args.requestId, companyId },
            include: { calendarEvent: true }
        });

        if (!request) return { error: `Agent request with ID ${args.requestId} not found.` };

        const action = (args.action || 'approve').toLowerCase();

        if (action === 'reject' || action === 'dismiss') {
            await (prisma as any).agentRequest.update({
                where: { id: request.id },
                data: {
                    status: 'rejected',
                    resolvedById: userId || null,
                    resolvedAt: new Date(),
                    resolutionNotes: args.notes || 'Rejected via Orbit AI Copilot'
                }
            });

            if (request.calendarEventId) {
                await (prisma as any).calendarEvent.delete({ where: { id: request.calendarEventId } }).catch(() => {});
            }

            return {
                success: true,
                requestId: request.id,
                status: 'rejected',
                message: `❌ Meeting request for **${request.customerName}** has been rejected.`
            };
        }

        if (action === 'reschedule') {
            const newDate = args.newTime ? new Date(args.newTime) : new Date(Date.now() + 24 * 60 * 60 * 1000);
            const durationMin = request.metadata?.durationMinutes || 30;
            const newEnd = new Date(newDate.getTime() + durationMin * 60 * 1000);

            if (request.calendarEventId) {
                await (prisma as any).calendarEvent.update({
                    where: { id: request.calendarEventId },
                    data: {
                        startDate: newDate,
                        endDate: newEnd,
                        startTime: newDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                        endTime: newEnd.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
                    }
                }).catch(() => {});
            }

            await (prisma as any).agentRequest.update({
                where: { id: request.id },
                data: {
                    scheduledStart: newDate,
                    scheduledEnd: newEnd,
                    status: 'confirmed',
                    resolvedById: userId || null,
                    resolvedAt: new Date(),
                    resolutionNotes: args.notes || 'Rescheduled via Orbit AI Copilot'
                }
            });

            return {
                success: true,
                requestId: request.id,
                status: 'confirmed',
                scheduledStart: newDate.toISOString(),
                message: `📅 Meeting for **${request.customerName}** has been rescheduled to **${newDate.toLocaleString()}**.`
            };
        }

        // Action: approve / confirm
        let calendarEventId = request.calendarEventId;
        if (!calendarEventId) {
            const start = request.scheduledStart || new Date(Date.now() + 24 * 60 * 60 * 1000);
            const end = request.scheduledEnd || new Date(start.getTime() + 30 * 60 * 1000);
            const event = await (prisma as any).calendarEvent.create({
                data: {
                    companyId,
                    title: `${request.topic} - ${request.customerName}`,
                    description: request.notes || `Meeting with ${request.customerName}`,
                    startDate: start,
                    endDate: end,
                    location: request.locationOrPlatform || 'Google Meet',
                    externalAttendees: request.customerEmail ? [request.customerEmail] : []
                }
            }).catch(() => null);
            calendarEventId = event?.id || null;
        }

        await (prisma as any).agentRequest.update({
            where: { id: request.id },
            data: {
                status: 'confirmed',
                calendarEventId,
                resolvedById: userId || null,
                resolvedAt: new Date(),
                resolutionNotes: args.notes || 'Approved & Confirmed via Orbit AI Copilot'
            }
        });

        return {
            success: true,
            requestId: request.id,
            status: 'confirmed',
            calendarEventId,
            message: `✅ Meeting request for **${request.customerName}** has been confirmed and added to 180 Calendar!`
        };
    }
};

export const scheduleMeetingTool: AIToolDefinition = {
    name: 'schedule_meeting',
    description: 'Schedules a calendar event or video conference meeting.',
    allowedRoles: ['all'],
    category: 'communications',
    parameters: {
        title: { type: 'string', description: 'Meeting title or subject', required: true },
        startTime: { type: 'string', description: 'ISO date string or start time', required: true },
        attendees: { type: 'array', description: 'List of attendee emails' }
    },
    execute: async (args, context) => {
        const { companyId } = context;
        if (!companyId) return { error: 'Company ID is required' };

        const start = new Date(args.startTime);
        const end = new Date(start.getTime() + 30 * 60 * 1000);

        const event = await (prisma as any).calendarEvent.create({
            data: {
                companyId,
                title: args.title,
                startDate: start,
                endDate: end,
                location: 'Google Meet',
                externalAttendees: args.attendees || []
            }
        }).catch(() => null);

        return {
            success: true,
            eventId: event?.id || `evt_${Date.now()}`,
            message: `📅 Meeting **"${args.title}"** scheduled for **${start.toLocaleString()}**.`
        };
    }
};

export const bookAppointmentTool: AIToolDefinition = {
    ...scheduleMeetingTool,
    name: 'book_appointment'
};

export const sendSmsConfirmationTool: AIToolDefinition = {
    name: 'send_sms_confirmation',
    description: 'Sends an SMS or WhatsApp confirmation notification to a client phone number.',
    allowedRoles: ['admin', 'employee'],
    category: 'communications',
    parameters: {
        phone: { type: 'string', description: 'Phone number', required: true },
        message: { type: 'string', description: 'SMS message text', required: true }
    },
    execute: async (args) => {
        return {
            success: true,
            phone: args.phone,
            message: `📱 SMS notification dispatched to **${args.phone}**:\n*"${args.message}"*`
        };
    }
};
